const cockpit = require('../cockpit')

if (cockpit.enabled === 'false') {
    console.log("Cockpit is disabled. You must set COCKPIT_ENABLED env to true")
    return
}

let error = new Error("Test generated by the Cockpit test command")

cockpit.publish(error)
