const debugmate = require('../debugmate')

if (debugmate.enabled === 'false') {
    console.log("Debugmate is disabled. You must set DEBUGMATE_ENABLED env to true")
    return
}

let error = new Error("Test generated by the Debugmate test command")

debugmate.publish(error)
